application: juice-toolkit
version: 2
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: templates/kovshenin/static

- url: /admin/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py

builtins:
- datastore_admin: on
